name: Build ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # This runs the build inside a pre-made Game Boy development container
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout Code Files
      uses: actions/checkout@v4

    - name: Build Graphics Tools
      run: |
        make -C tools/

    - name: Assemble GBC ROM
      run: |
        make

    - name: Save Playable ROM File
      uses: actions/upload-artifact@v4
      with:
        name: pokeyellow-rom
        path: |
          *.gbc
          *.sym
          
